### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by legomushroom** [github/gh-net#27]
This issue tracks Windows support for the extension.

- [x] Windows 10
- [x] Windows 11

**Comment by homeaidepi** [comment]
Personally will be a huge fan of the Windows support. Please let me know how I can help and thanks for all youre doing to help bring Enterprise grade networking to Codespaces.

**Comment by legomushroom** [comment]
`Windows` for `AMD64` machines support released in [`v0.12.2`](https://github.com/github/gh-net/releases/tag/v0.12.2) 🚀
Please let me know if you need support for `ARM64` or `i386` architectures.

cc @homeaidepi
